mysql:
  path: '127.0.0.1'
  port: '3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'ass'
  username: 'root'
  password: '123456'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

zap:
  level: 'info'
  format: 'console'
  prefix: '[association]'
  director: 'log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

redis:
  db: 0
  addr: '127.0.0.1:6379'
  password: ''

jwt:
  signing-key: 'tanyilin'
  expires-time: 604800
  buffer-time: 86400
  issuer: 'tanyilin'

casbin:
  model-path: './resource/rbac_model.conf'



system:
  ip2location_path: './IP2LOCATION-LITE-DB5.IPV6.BIN'